spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:}
    port: ${RABBITMQ_PORT:}
    username: ${RABBITMQ_USERNAME:}
    password: ${RABBITMQ_PASSWORD:}
    virtual-host: ${DEMO_RABBITMQ_VHOST:}
    cache:
      channel:
        size: ${RABBITMQ_CACHE_CHANNEL_SIZE:500} # default 500
      connection:
        mode: channel
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/shipment.db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
server:
  port: 8105