spring:
  application:
    name: order-service
  rabbitmq:
    host: ${RABBITMQ_HOST:}
    port: ${RABBITMQ_PORT:}
    username: ${RABBITMQ_USERNAME:}
    password: ${RABBITMQ_PASSWORD:}
    virtual-host: ${DEMO_RABBITMQ_VHOST:}
    cache:
      channel:
        size: ${RABBITMQ_CACHE_CHANNEL_SIZE:500} # default 500
      connection:
        mode: channel
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/order.db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # Always sample during dev
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
server:
  port: 8102